"""Provider appeal endpoints — appeal letter generation, listing, status tracking."""

from __future__ import annotations

import base64
import io
import json

from fastapi import APIRouter, HTTPException, Request

from routers.provider_shared import (
    _get_supabase, _get_authenticated_user, _verify_admin,
    _call_claude,
    GenerateAppealRequest, GenerateAppealBatchRequest, UpdateAppealStatusRequest,
)

router = APIRouter(tags=["provider"])


# ---------------------------------------------------------------------------
# Appeal Letter Generation
# ---------------------------------------------------------------------------

APPEAL_SYSTEM_PROMPT = """You are a medical billing appeals specialist. Generate a formal appeal letter to a health insurance payer requesting reprocessing of a denied or underpaid claim.

The letter must:
1. Be addressed to the payer's appeals department
2. Reference the specific claim ID, patient name, date of service, CPT code, and denial reason
3. Clearly state why the denial should be overturned
4. Cite specific CMS guidelines, NCCI rules, AMA CPT guidelines, or payer contract terms as applicable for this denial code
5. Reference the contracted rate when available
6. Request reprocessing and payment at the contracted rate
7. Use a professional, firm tone — not adversarial
8. Include standard closing with practice contact information

Common denial code guidance:
- CO-16 (Claim/service lacks information): Usually a documentation deficiency. Argue that documentation was provided or offer to resubmit.
- CO-45 (Charge exceeds fee schedule): Contract dispute. Reference the specific contracted rate.
- CO-97 (Payment adjusted — already adjudicated): Duplicate processing issue. Provide proof of distinct service.
- OA-18 (Exact duplicate claim/service): Show services were distinct (different dates, modifiers, or medical necessity).
- CO-4 (Procedure code inconsistent with modifier): Explain medical necessity for the modifier used.
- PR-1 (Deductible amount): Patient responsibility — generally not appealable, note if applied incorrectly.
- CO-50 (Non-covered service): Argue medical necessity with clinical documentation.

Return ONLY valid JSON:
{
  "letter_html": "<full HTML-formatted appeal letter with proper paragraphs, line breaks, and formatting>",
  "letter_text": "plain text version of the letter",
  "cms_references": ["list of specific CMS/guideline references cited"],
  "appeal_strength": "high|medium|low",
  "appeal_strength_reason": "brief explanation of why this appeal is likely/unlikely to succeed"
}"""


def _generate_appeal_pdf(letter_text: str, practice_name: str, payer_name: str, claim_id: str) -> bytes:
    """Generate a formatted PDF appeal letter using ReportLab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, HRFlowable
    from datetime import datetime

    TEAL = colors.HexColor("#0D9488")
    NAVY = colors.HexColor("#1E293B")

    styles = getSampleStyleSheet()
    s_header = ParagraphStyle("AppealHeader", parent=styles["Normal"], fontSize=10, textColor=TEAL, spaceAfter=2)
    s_body = ParagraphStyle("AppealBody", parent=styles["Normal"], fontSize=11, leading=16, textColor=NAVY)
    s_small = ParagraphStyle("AppealSmall", parent=styles["Normal"], fontSize=9, leading=12, textColor=colors.HexColor("#64748B"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=1 * inch, rightMargin=1 * inch,
        topMargin=1 * inch, bottomMargin=1 * inch,
    )

    story = []

    # Letterhead
    story.append(Paragraph(practice_name, ParagraphStyle("PracticeName", parent=s_body, fontSize=14, textColor=NAVY, fontName="Helvetica-Bold")))
    story.append(Paragraph(f"Re: Appeal — Claim {claim_id}", s_header))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", s_header))
    story.append(HRFlowable(width="100%", thickness=1, color=TEAL, spaceAfter=16, spaceBefore=8))

    # Letter body
    for line in letter_text.split("\n"):
        if line.strip():
            story.append(Paragraph(line.strip(), s_body))
            story.append(Spacer(1, 6))
        else:
            story.append(Spacer(1, 12))

    # Footer
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1"), spaceAfter=8))
    story.append(Paragraph("Generated by Parity Health — CivicScale Benchmark Infrastructure", s_small))
    story.append(Paragraph("This letter template should be reviewed and customized before sending.", s_small))

    doc.build(story)
    return buf.getvalue()


@router.post("/generate-appeal")
async def generate_appeal(req: GenerateAppealRequest, request: Request):
    """Generate a formal appeal letter for a denied or underpaid claim."""
    user = await _get_authenticated_user(request)

    prompt_data = json.dumps({
        "claim_id": req.claim_id,
        "denial_code": req.denial_code,
        "cpt_code": req.cpt_code,
        "billed_amount": req.billed_amount,
        "payer_name": req.payer_name,
        "date_of_service": req.date_of_service,
        "practice_name": req.practice_name,
        "practice_address": req.practice_address,
        "provider_name": req.provider_name,
        "npi": req.npi,
        "patient_name": req.patient_name,
    })

    result = _call_claude(
        system_prompt=APPEAL_SYSTEM_PROMPT,
        user_content=prompt_data,
        max_tokens=8192,
    )

    if not result:
        raise HTTPException(status_code=500, detail="Failed to generate appeal letter")

    # Generate PDF
    pdf_bytes = _generate_appeal_pdf(
        letter_text=result.get("letter_text", ""),
        practice_name=req.practice_name or "Practice",
        payer_name=req.payer_name or "Payer",
        claim_id=req.claim_id or "N/A",
    )
    pdf_base64 = base64.b64encode(pdf_bytes).decode("utf-8")

    # Save appeal record
    sb = _get_supabase()
    appeal_record = {
        "user_id": str(user.id),
        "subscription_id": req.subscription_id,
        "audit_id": req.audit_id,
        "claim_id": req.claim_id,
        "payer_name": req.payer_name,
        "denial_code": req.denial_code,
        "cpt_code": req.cpt_code,
        "amount": req.billed_amount,
        "status": "drafted",
        "letter_text": result.get("letter_text", ""),
        "letter_html": result.get("letter_html", ""),
        "appeal_strength": result.get("appeal_strength", ""),
        "cms_references": result.get("cms_references", []),
    }

    appeal_id = None
    try:
        ins = sb.table("provider_appeals").insert(appeal_record).execute()
        if ins.data and len(ins.data) > 0:
            appeal_id = ins.data[0]["id"]
    except Exception as exc:
        print(f"[GenerateAppeal] Failed to save appeal record: {exc}")

    return {
        "appeal_id": appeal_id,
        "letter_html": result.get("letter_html", ""),
        "letter_text": result.get("letter_text", ""),
        "pdf_base64": pdf_base64,
        "cms_references": result.get("cms_references", []),
        "appeal_strength": result.get("appeal_strength", ""),
        "appeal_strength_reason": result.get("appeal_strength_reason", ""),
    }


@router.post("/generate-appeal-batch")
async def generate_appeal_batch(req: GenerateAppealBatchRequest, request: Request):
    """Generate appeal letters for multiple denials at once."""
    user = await _get_authenticated_user(request)

    results = []
    for denial in req.denials:
        prompt_data = json.dumps({
            "claim_id": denial.get("claim_id", ""),
            "denial_code": denial.get("denial_code", ""),
            "cpt_code": denial.get("cpt_code", ""),
            "billed_amount": denial.get("billed_amount", 0),
            "payer_name": denial.get("payer_name", ""),
            "date_of_service": denial.get("date_of_service", ""),
            "practice_name": denial.get("practice_name", ""),
            "practice_address": denial.get("practice_address", ""),
            "provider_name": denial.get("provider_name", ""),
            "npi": denial.get("npi", ""),
            "patient_name": denial.get("patient_name", ""),
        })

        result = _call_claude(
            system_prompt=APPEAL_SYSTEM_PROMPT,
            user_content=prompt_data,
            max_tokens=8192,
        )

        if not result:
            results.append({"error": True, "claim_id": denial.get("claim_id", ""), "detail": "Generation failed"})
            continue

        # Generate PDF
        pdf_bytes = _generate_appeal_pdf(
            letter_text=result.get("letter_text", ""),
            practice_name=denial.get("practice_name", "Practice"),
            payer_name=denial.get("payer_name", "Payer"),
            claim_id=denial.get("claim_id", "N/A"),
        )
        pdf_base64 = base64.b64encode(pdf_bytes).decode("utf-8")

        # Save appeal record
        sb = _get_supabase()
        appeal_record = {
            "user_id": str(user.id),
            "subscription_id": req.subscription_id,
            "audit_id": req.audit_id,
            "claim_id": denial.get("claim_id", ""),
            "payer_name": denial.get("payer_name", ""),
            "denial_code": denial.get("denial_code", ""),
            "cpt_code": denial.get("cpt_code", ""),
            "amount": denial.get("billed_amount", 0),
            "status": "drafted",
            "letter_text": result.get("letter_text", ""),
            "letter_html": result.get("letter_html", ""),
            "appeal_strength": result.get("appeal_strength", ""),
            "cms_references": result.get("cms_references", []),
        }

        appeal_id = None
        try:
            ins = sb.table("provider_appeals").insert(appeal_record).execute()
            if ins.data and len(ins.data) > 0:
                appeal_id = ins.data[0]["id"]
        except Exception:
            pass

        results.append({
            "appeal_id": appeal_id,
            "claim_id": denial.get("claim_id", ""),
            "denial_code": denial.get("denial_code", ""),
            "cpt_code": denial.get("cpt_code", ""),
            "letter_html": result.get("letter_html", ""),
            "letter_text": result.get("letter_text", ""),
            "pdf_base64": pdf_base64,
            "appeal_strength": result.get("appeal_strength", ""),
        })

    return {"appeals": results, "count": len(results)}


@router.get("/appeals")
async def list_appeals(request: Request):
    """List all appeals for the authenticated user."""
    user = await _get_authenticated_user(request)

    sb = _get_supabase()
    result = sb.table("provider_appeals") \
        .select("*") \
        .eq("user_id", str(user.id)) \
        .order("created_at", desc=True) \
        .execute()

    return {"appeals": result.data or []}


@router.post("/appeals/update-status")
async def update_appeal_status(req: UpdateAppealStatusRequest, request: Request):
    """Update the status of an appeal (drafted, sent, won, lost, pending)."""
    user = await _get_authenticated_user(request)

    valid_statuses = {"drafted", "sent", "won", "lost", "pending"}
    if req.status not in valid_statuses:
        raise HTTPException(status_code=400, detail=f"Status must be one of: {', '.join(valid_statuses)}")

    sb = _get_supabase()

    # Verify ownership
    row = sb.table("provider_appeals").select("user_id").eq("id", req.appeal_id).execute()
    if not row.data:
        raise HTTPException(status_code=404, detail="Appeal not found")
    if row.data[0].get("user_id") != str(user.id):
        # Also allow admin
        try:
            await _verify_admin(request)
        except Exception:
            raise HTTPException(status_code=403, detail="Not authorized")

    update_data = {"status": req.status}
    if req.outcome_amount is not None:
        update_data["outcome_amount"] = req.outcome_amount
    if req.notes is not None:
        update_data["notes"] = req.notes

    sb.table("provider_appeals").update(update_data).eq("id", req.appeal_id).execute()

    return {"status": "ok", "appeal_id": req.appeal_id, "new_status": req.status}
