-- Migration 087: the posture function, the four remaining open policies, and
-- the grant floor for every table in public.
--
-- WHY THIS EXISTS
-- ---------------
-- 086 closed fourteen tables found by a pg_policies query. That query could
-- not have found provider_appeal_letters -- eight appeal letters with patient
-- names, RLS enabled, NO policy, anon and authenticated holding full DML --
-- because a table with no policy appears in no policy listing. It was closed
-- only by RLS's default-deny; one DISABLE ROW LEVEL SECURITY away from open.
-- So the instrument is rebuilt to enumerate TABLES (verify/db_posture.py),
-- and this migration is what brings every table to the floor its bucket
-- requires. TRUNCATE is not subject to RLS and anon/authenticated held it on
-- every table CREATE TABLE made; no REST verb reaches it, but it has no
-- legitimate holder either.
--
-- 1. public.db_posture(): SECURITY DEFINER, EXECUTE for service_role only.
--    One JSON object per table: RLS state, every policy (cmd, roles, qual,
--    with_check), grants to anon/authenticated/service_role/PUBLIC.
--    tests/verify/test_db_posture.py calls it over RPC in CI and fails on
--    any table outside service_role_only / public_read / user_scoped /
--    gated_read.
--
-- 2. broker_client_benchmarks -- "public read by share token", FOR SELECT TO
--    anon USING (true). The name claims a token check; the qual has none:
--    anon read all seven brokers' client benchmarks (PEPM, carrier, company).
--    DECISION: service-role-only, mediated by the backend. The token check
--    already exists in one place -- GET /api/employer/shared-report/
--    {share_token} (employer_shared_report.py) reads with the service key and
--    filters by token -- and the frontend never reads this table directly
--    (grep of frontend/src .from(): profiles, signal_*, topic_* only).
--    Putting the token in the qual would require PostgREST to *force* a
--    client to filter by token, which a USING clause cannot do without a
--    per-request setting; the backend route is the enforcement point.
--
-- 3. "Allow anonymous inserts" WITH CHECK (true) on employer_benchmark_
--    sessions, employer_claims_uploads, employer_scorecard_sessions. Grep on
--    2026-09-15: every insert is in routers/ (employer_benchmark.py:175,
--    employer_scorecard.py:273, broker.py) through _get_supabase(), the
--    service key; nothing in frontend/src inserts. An anon INSERT path on an
--    uploads table is a free storage channel for anyone with the key. Dropped.
--
-- 4. signal_events "Authenticated users can insert events" WITH CHECK (true).
--    Written by routers/signal_events.py:76 through supabase_client.supabase
--    (service key) after validating event_type and session_id; the frontend
--    posts to /api/signal/events, never to the table. A signed-in user has no
--    legitimate direct write. Dropped; the name claimed a scope ("authenticated
--    users") the with_check did not enforce.
--
-- 5. The grant floor, 136 statements, GENERATED by
--    verify.db_posture.hygiene_statements() from the 2026-09-15 posture
--    snapshot with the four policies above treated as dropped. Rule: a client
--    role keeps exactly the DML some admitting policy needs (user_scoped
--    tables keep what their auth.uid() policies use; public_read and
--    gated_read tables keep SELECT); everything else, and TRUNCATE /
--    REFERENCES / TRIGGER everywhere, is revoked. Explicit rather than a DO
--    loop so a reviewer sees which grant leaves which table.
--    Simulated against the snapshot: FAIL 0 / public_read 9 / gated_read 13 /
--    user_scoped 8 / service_role_only 58.
--
-- Log check before revoking: in the last 24h and on 2026-08-31 the only
-- non-service REST traffic outside signal_*/topic_* (gated reads, kept) was
-- the operator's own 2026-09-15 probes. WHU's subscriber sync uses the
-- service key (scripts/whatholdsup/sync_subscribers.py:74).

-- ---------------------------------------------------------------------------
-- 1. the posture function
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.db_posture()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
select coalesce(jsonb_agg(row_to_json(t)::jsonb order by t.table_name), '[]'::jsonb) from (
  select c.relname as table_name, c.relrowsecurity as rls_enabled, c.relforcerowsecurity as rls_forced,
    coalesce((select jsonb_agg(jsonb_build_object('name', p.policyname, 'cmd', p.cmd, 'permissive', p.permissive,
                                                  'roles', p.roles, 'qual', p.qual, 'with_check', p.with_check)
                               order by p.policyname)
              from pg_policies p where p.schemaname = 'public' and p.tablename = c.relname), '[]'::jsonb) as policies,
    coalesce((select jsonb_object_agg(g.grantee, g.privs)
              from (select grantee, jsonb_agg(privilege_type order by privilege_type) as privs
                    from information_schema.role_table_grants x
                    where x.table_schema = 'public' and x.table_name = c.relname
                      and grantee in ('anon', 'authenticated', 'service_role', 'PUBLIC')
                    group by grantee) g), '{}'::jsonb) as grants
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')
) t
$fn$;
REVOKE EXECUTE ON FUNCTION public.db_posture() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.db_posture() TO service_role;
COMMENT ON FUNCTION public.db_posture() IS 'Every table in public with RLS state, policies and client grants; read by tests/verify/test_db_posture.py (service_role only).';

-- ---------------------------------------------------------------------------
-- 2-4. the four open policies
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "public read by share token" ON public.broker_client_benchmarks;
DROP POLICY IF EXISTS "Service role full access" ON public.broker_client_benchmarks;
CREATE POLICY "Service role full access" ON public.broker_client_benchmarks FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous inserts on employer_benchmark_sessions" ON public.employer_benchmark_sessions;
DROP POLICY IF EXISTS "Allow anonymous inserts on employer_claims_uploads" ON public.employer_claims_uploads;
DROP POLICY IF EXISTS "Allow anonymous inserts on employer_scorecard_sessions" ON public.employer_scorecard_sessions;

DROP POLICY IF EXISTS "Authenticated users can insert events" ON public.signal_events;

-- ---------------------------------------------------------------------------
-- 5. the grant floor (generated; see header)
-- ---------------------------------------------------------------------------
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.analyst_practice_assignments FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.analyst_practice_assignments FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.benchmark_observations FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.benchmark_observations FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.bill_line_items FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.bill_line_items FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_835_jobs FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_835_jobs FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_claim_lines FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_claim_lines FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_companies FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_companies FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_practices FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_practices FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_subscriptions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_subscriptions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_users FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_company_users FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_contracts FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_contracts FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_escalation_practices FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_escalation_practices FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_escalations FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.billing_escalations FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.bills FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.bills FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_accounts FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_accounts FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_client_benchmarks FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_client_benchmarks FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_commissions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_commissions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_employer_links FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_employer_links FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_prospect_benchmarks FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_prospect_benchmarks FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_referral_credits FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_referral_credits FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_referrals FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.broker_referrals FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.clfs_rates_historical FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.clfs_rates_historical FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.companies FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.companies FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.company_invitations FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.company_invitations FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.company_users FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.company_users FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.data_versions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.data_versions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.deletion_requests FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.deletion_requests FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_benchmark_sessions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_benchmark_sessions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_claims_uploads FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_claims_uploads FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_scorecard_sessions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_scorecard_sessions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_subscriptions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_subscriptions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_trends_cache FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.employer_trends_cache FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.health_sbc_uploads FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.health_sbc_uploads FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.opps_rates_historical FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.opps_rates_historical FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.otp_codes FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.otp_codes FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payer_performance_history FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payer_performance_history FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.pfs_rates_historical FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.pfs_rates_historical FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pharmacy_benchmarks FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pharmacy_benchmarks FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pharmacy_nadac FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pharmacy_nadac FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.platform_cases FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.platform_cases FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.practice_portal_settings FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.practice_portal_settings FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.profiles FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.profiles FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_appeal_letters FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_appeal_letters FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_appeal_outcomes FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_appeal_outcomes FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_benchmark_observations FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_benchmark_observations FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_denial_patterns FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.provider_denial_patterns FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.rate_schedule_versions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.rate_schedule_versions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.sessions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.sessions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_analytical_profiles FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_analytical_profiles FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_composites FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_composites FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_scores FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_scores FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_sources FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claim_sources FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claims FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_claims FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_consensus FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_consensus FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_cpt_mappings FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_cpt_mappings FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_denial_playbook FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_denial_playbook FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.signal_events FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.signal_events FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_evidence_updates FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_evidence_updates FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_issues FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_issues FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.signal_notification_preferences FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.signal_notification_preferences FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE ON public.signal_notifications FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE ON public.signal_notifications FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_platform_metrics FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_platform_metrics FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_sources FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_sources FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_subscriptions FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_subscriptions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_summaries FROM anon;
REVOKE DELETE, INSERT, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_summaries FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_topic_requests FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE, UPDATE ON public.signal_topic_requests FROM authenticated;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.signal_topic_subscriptions FROM anon;
REVOKE DELETE, REFERENCES, TRIGGER, TRUNCATE ON public.signal_topic_subscriptions FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatholdsup_subscribers FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatholdsup_subscribers FROM authenticated;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatholdsup_unsubscribes FROM anon;
REVOKE DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatholdsup_unsubscribes FROM authenticated;
