"""
Parity Signal: Summary Generation.

Final pipeline step. Assembles claims, scores, and consensus into a structured
JSON summary (for UI) and a plain-language narrative text (for reading).

The structured data (stats, categories, top claims) is computed deterministically
in Python. Only the overall narrative and per-category key takeaways are
generated by Claude (one API call).

Summaries are versioned — re-running creates a new version rather than
overwriting, supporting the evidence update workflow.

Usage:
    cd backend && source venv/bin/activate
    export $(grep -v '^#' .env | xargs)

    python scripts/signal/generate_summary.py --dry-run
    python scripts/signal/generate_summary.py
    python scripts/signal/generate_summary.py   # creates version 2
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# Add backend/ to sys.path so we can import supabase_client
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from topic_config import get_topic

GENERATION_MODEL = "claude-sonnet-4-6"
BACKOFF_DELAYS = [2, 5, 10]
TOP_CLAIMS_PER_CATEGORY = 5


# ---------------------------------------------------------------------------
# Anthropic Claude client (lazy singleton)
# ---------------------------------------------------------------------------

_anthropic_client = None


def _get_anthropic_client():
    """Lazy singleton for Anthropic client. Reads ANTHROPIC_API_KEY from env."""
    global _anthropic_client
    if _anthropic_client is None:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            print("ERROR: ANTHROPIC_API_KEY not set.")
            print("  export ANTHROPIC_API_KEY=your_key_here")
            sys.exit(1)
        import anthropic
        _anthropic_client = anthropic.Anthropic(api_key=api_key)
    return _anthropic_client


def _call_claude(system_prompt: str, user_content: str, max_tokens: int = 4096) -> dict | list | None:
    """Call Claude API with retry on 529, return parsed JSON."""
    client = _get_anthropic_client()
    response = None

    for attempt in range(len(BACKOFF_DELAYS) + 1):
        try:
            response = client.messages.create(
                model=GENERATION_MODEL,
                max_tokens=max_tokens,
                temperature=0,
                system=system_prompt,
                messages=[{"role": "user", "content": user_content}],
            )
            break
        except Exception as exc:
            err_str = str(exc)
            if "529" in err_str and attempt < len(BACKOFF_DELAYS):
                delay = BACKOFF_DELAYS[attempt]
                print(f"  [RETRY] Claude overloaded (529), attempt {attempt + 1}/{len(BACKOFF_DELAYS)} in {delay}s...")
                time.sleep(delay)
                continue
            print(f"  [ERROR] Claude API error: {exc}")
            return None

    if response is None:
        return None

    raw_text = ""
    for block in response.content:
        if hasattr(block, "text"):
            raw_text += block.text

    raw_text = raw_text.strip()
    if raw_text.startswith("```"):
        raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text)
        raw_text = re.sub(r"\s*```\s*$", "", raw_text)
    raw_text = raw_text.strip()

    try:
        return json.loads(raw_text)
    except json.JSONDecodeError:
        print(f"  [ERROR] Invalid JSON from Claude: {raw_text[:500]}")
        return None


# ---------------------------------------------------------------------------
# Supabase helpers
# ---------------------------------------------------------------------------

def _get_supabase():
    """Import and return the Supabase client, or exit with message."""
    from supabase_client import supabase as sb
    if sb is None:
        print("ERROR: Supabase client not initialized.")
        print("Set SUPABASE_SERVICE_KEY environment variable before running.")
        sys.exit(1)
    return sb


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_pipeline_data(sb, issue_slug: str) -> dict:
    """Load all pipeline data needed for summary generation.

    Returns dict with: issue_id, issue_title, claims, composites, consensus, source_count
    """
    resp = sb.table("signal_issues").select("id, title").eq("slug", issue_slug).execute()
    if not resp.data:
        print(f"ERROR: No '{issue_slug}' issue found. Run earlier pipeline steps first.")
        sys.exit(1)
    issue = resp.data[0]
    issue_id = issue["id"]

    # Count sources
    resp = (
        sb.table("signal_sources")
        .select("id", count="exact")
        .eq("issue_id", issue_id)
        .execute()
    )
    source_count = resp.count or 0

    # Load all claims
    resp = (
        sb.table("signal_claims")
        .select("id, claim_text, category, specificity")
        .eq("issue_id", issue_id)
        .execute()
    )
    claims = resp.data or []

    # Load composites
    claim_ids = [c["id"] for c in claims]
    composites: dict[str, dict] = {}
    chunk_size = 50
    for i in range(0, len(claim_ids), chunk_size):
        chunk = claim_ids[i:i + chunk_size]
        resp = (
            sb.table("signal_claim_composites")
            .select("claim_id, composite_score, evidence_category")
            .in_("claim_id", chunk)
            .execute()
        )
        for comp in (resp.data or []):
            composites[comp["claim_id"]] = comp

    # Load claim-source counts
    source_counts: dict[str, int] = defaultdict(int)
    for i in range(0, len(claim_ids), chunk_size):
        chunk = claim_ids[i:i + chunk_size]
        resp = (
            sb.table("signal_claim_sources")
            .select("claim_id")
            .in_("claim_id", chunk)
            .execute()
        )
        for row in (resp.data or []):
            source_counts[row["claim_id"]] += 1

    # Load consensus
    resp = (
        sb.table("signal_consensus")
        .select("category, consensus_status, summary_text, arguments_for, arguments_against")
        .eq("issue_id", issue_id)
        .execute()
    )
    consensus = {row["category"]: row for row in (resp.data or [])}

    # Attach composites and source counts to claims
    for claim in claims:
        comp = composites.get(claim["id"])
        if comp:
            claim["composite_score"] = float(comp["composite_score"])
            claim["evidence_category"] = comp["evidence_category"]
        else:
            claim["composite_score"] = None
            claim["evidence_category"] = None
        claim["source_count"] = source_counts.get(claim["id"], 0)

    print(f"Loaded pipeline data:")
    print(f"  Issue: {issue['title']}")
    print(f"  Sources: {source_count}")
    print(f"  Claims: {len(claims)} ({len(composites)} scored)")
    print(f"  Consensus mappings: {len(consensus)}")

    return {
        "issue_id": issue_id,
        "issue_title": issue["title"],
        "claims": claims,
        "composites": composites,
        "consensus": consensus,
        "source_count": source_count,
    }


# ---------------------------------------------------------------------------
# Stats and category assembly (deterministic Python)
# ---------------------------------------------------------------------------

def build_stats(data: dict) -> dict:
    """Compute aggregate stats from pipeline data."""
    claims = data["claims"]
    scored = [c for c in claims if c.get("composite_score") is not None]

    cat_counts = defaultdict(int)
    for c in scored:
        cat_counts[c["evidence_category"]] += 1

    return {
        "total_sources": data["source_count"],
        "total_claims": len(claims),
        "scored_claims": len(scored),
        "strong_claims": cat_counts.get("strong", 0),
        "moderate_claims": cat_counts.get("moderate", 0),
        "mixed_claims": cat_counts.get("mixed", 0),
        "weak_claims": cat_counts.get("weak", 0),
    }


def build_category_sections(data: dict, categories: list[str]) -> list[dict]:
    """Assemble per-category sections with top claims."""
    claims = data["claims"]
    consensus = data["consensus"]

    # Group by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for c in claims:
        by_cat[c.get("category", categories[-1])].append(c)

    sections = []
    for cat in categories:
        group = by_cat.get(cat, [])
        scored = [c for c in group if c.get("composite_score") is not None]
        scored.sort(key=lambda c: c["composite_score"], reverse=True)

        avg_composite = 0.0
        if scored:
            avg_composite = round(sum(c["composite_score"] for c in scored) / len(scored), 2)

        # Top N claims
        top_claims = []
        for c in scored[:TOP_CLAIMS_PER_CATEGORY]:
            top_claims.append({
                "claim_text": c["claim_text"],
                "composite_score": c["composite_score"],
                "evidence_category": c["evidence_category"],
                "source_count": c.get("source_count", 0),
            })

        cons = consensus.get(cat, {})
        section = {
            "name": cat,
            "consensus_status": cons.get("consensus_status", "uncertain"),
            "consensus_summary": cons.get("summary_text", ""),
            "claim_count": len(group),
            "scored_count": len(scored),
            "avg_composite": avg_composite,
            "top_claims": top_claims,
        }

        if cons.get("consensus_status") == "debated":
            section["arguments_for"] = cons.get("arguments_for", "")
            section["arguments_against"] = cons.get("arguments_against", "")

        sections.append(section)

    return sections


# ---------------------------------------------------------------------------
# Claude narrative generation (one API call)
# ---------------------------------------------------------------------------

def _build_narrative_system_prompt(topic: dict) -> str:
    """Build the narrative generation system prompt dynamically from topic config."""
    categories_json = ",\n    ".join(f'"{cat}": "key takeaway for this category (see structure rules below)"' for cat in topic["categories"])
    return f"""You are a science communicator writing for a general audience. You are generating a summary of the current evidence on {topic['prompt_subject']}.

Context: {topic['prompt_detail']}

## Core Rules
- Do NOT express opinions or recommendations
- Describe evidence strength and consensus, not truth
- Be specific: include key numbers from the top claims where relevant
- Do NOT use phrases like "our analysis shows" — describe what the evidence shows

## Plain-Language Accessibility Rules

These rules apply to ALL text you generate — overall_summary, every category_takeaways value, and any descriptions.

### Drug and Treatment Names
- Always include brand names parenthetically on first use: "semaglutide (Ozempic, Wegovy)" not just "semaglutide"
- For drug classes, include a plain-language explanation on first use: "CDK4/6 inhibitors (drugs that block specific proteins that help cancer cells divide)"
- Never use abbreviations like T-DXd without the full name and brand: "trastuzumab deruxtecan (Enhertu)"

### Technical Terms
- Define every clinical term on first use in parentheses: "progression-free survival (how long patients lived before their cancer worsened)"
- Spell out all acronyms on first use: "HR+ (hormone receptor-positive)" not just "HR+"
- Avoid jargon when a plain word exists: "side effects" not "adverse events", "spread" not "metastasized" (or use both: "metastasized (spread to other parts of the body)")

### Clinical Data Translation
- Every time a statistic is cited, follow it with a plain-language interpretation: "median overall survival of 22.4 months vs 16.4 months — meaning patients on the newer drug lived roughly 6 months longer on average"
- For relative risk reductions, also state the absolute numbers: "a 20% reduction in major cardiovascular events — in practical terms, about 2 fewer events per 100 patients treated"
- For NNT or similar metrics, translate: "roughly 1 in every 50 patients will benefit"

### Structure
- Begin each category_takeaways value with a single "Bottom line" sentence in everyday language before any technical details
- End each category_takeaways value with a "What to watch" sentence about emerging evidence or open questions
- The overall_summary opening sentence should be understandable by someone with no medical, scientific, or policy background

## Length
- overall_summary: 2-3 paragraphs (~400-500 words)
- Each category_takeaways value: 2-4 sentences (bottom line + details + what to watch)

## Output Format

Return a JSON object:
{{
  "overall_summary": "2-3 paragraph plain-language narrative. Start with a sentence anyone can understand. Cover all categories. End with what remains debated or uncertain.",
  "category_takeaways": {{
    {categories_json}
  }}
}}"""


def _build_glossary_system_prompt() -> str:
    """System prompt for glossary extraction."""
    return """You are a medical/scientific glossary writer. Given a summary text, extract every technical term, drug name, acronym, or clinical concept that a general reader might not understand.

For each term, write a plain-English definition in 1 sentence, under 20 words.

Return a JSON object where keys are terms (lowercase) and values are definitions.

Example:
{
  "semaglutide": "An injectable medication that mimics a gut hormone to reduce appetite and blood sugar.",
  "progression-free survival": "How long a patient lives before their disease gets worse.",
  "HR+": "Hormone receptor-positive; a breast cancer type that grows in response to hormones."
}

Rules:
- Include drug names (generic and brand), acronyms, clinical terms, statistical concepts, and medical procedures
- Use plain language a high school student would understand
- Keep each definition under 20 words
- Do NOT include common English words that happen to appear in a medical context"""


def _build_narrative_user_content(stats: dict, sections: list[dict], topic: dict) -> str:
    """Build the user-content block with all evidence data for narrative generation."""
    parts = [
        f"Evidence Summary Data for {topic['title']}",
        f"",
        f"Overall stats:",
        f"  {stats['total_sources']} sources analyzed",
        f"  {stats['total_claims']} claims extracted, {stats['scored_claims']} scored",
        f"  Evidence strength: {stats['strong_claims']} strong, {stats['moderate_claims']} moderate, "
        f"{stats['mixed_claims']} mixed, {stats['weak_claims']} weak",
        f"",
    ]

    for section in sections:
        parts.append(f"--- {section['name'].upper()} ---")
        parts.append(f"Status: {section['consensus_status']}")
        parts.append(f"Claims: {section['claim_count']} ({section['scored_count']} scored, avg score {section['avg_composite']})")
        if section.get("consensus_summary"):
            parts.append(f"Consensus: {section['consensus_summary']}")

        if section.get("arguments_for"):
            parts.append(f"Arguments for: {section['arguments_for']}")
            parts.append(f"Arguments against: {section['arguments_against']}")

        parts.append(f"Top claims:")
        for tc in section["top_claims"]:
            parts.append(f"  [{tc['composite_score']:.2f} {tc['evidence_category']}] {tc['claim_text']}")
        parts.append("")

    return "\n".join(parts)


def generate_narrative(stats: dict, sections: list[dict], topic: dict) -> dict | None:
    """Send assembled data to Claude for narrative generation.

    Returns {overall_summary, category_takeaways} or None on failure.
    """
    narrative_prompt = _build_narrative_system_prompt(topic)
    user_text = _build_narrative_user_content(stats, sections, topic)
    return _call_claude(narrative_prompt, user_text, max_tokens=8192)


def generate_glossary(summary_text: str, category_takeaways: dict) -> dict | None:
    """Extract technical terms from generated summary and produce a glossary.

    Returns {term: definition, ...} or None on failure.
    """
    all_text = summary_text + "\n\n"
    for takeaway in category_takeaways.values():
        all_text += takeaway + "\n"

    system_prompt = _build_glossary_system_prompt()
    user_content = f"Extract a glossary of technical terms from this summary text:\n\n{all_text}"
    return _call_claude(system_prompt, user_content, max_tokens=4096)


# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------

def get_next_version(sb, issue_id: str) -> int:
    """Get the next version number for this issue's summaries."""
    resp = (
        sb.table("signal_summaries")
        .select("version")
        .eq("issue_id", issue_id)
        .order("version", desc=True)
        .limit(1)
        .execute()
    )
    if resp.data:
        return resp.data[0]["version"] + 1
    return 1


def store_summary(sb, issue_id: str, version: int, summary_json: dict, summary_text: str) -> bool:
    """Insert summary row. Returns True on success."""
    row = {
        "issue_id": issue_id,
        "version": version,
        "summary_json": summary_json,
        "summary_text": summary_text,
        "generation_model": GENERATION_MODEL,
    }
    try:
        sb.table("signal_summaries").insert(row).execute()
        return True
    except Exception as exc:
        print(f"  [ERROR] Failed to insert summary: {exc}")
        return False


# ---------------------------------------------------------------------------
# CLI orchestrator
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate structured summary from scored claims and consensus."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show assembled data without API call or DB write",
    )
    parser.add_argument(
        "--issue-slug",
        type=str,
        default="glp1-drugs",
        help="Topic slug (default: glp1-drugs)",
    )
    args = parser.parse_args()

    issue_slug = args.issue_slug
    topic = get_topic(issue_slug)
    categories = topic["categories"]
    print(f"Topic: {topic['title']} ({issue_slug})")

    sb = _get_supabase()
    data = load_pipeline_data(sb, issue_slug)

    # Build structured sections
    stats = build_stats(data)
    sections = build_category_sections(data, categories)
    next_version = get_next_version(sb, data["issue_id"])

    # --- Dry run ---
    if args.dry_run:
        print(f"\n--- DRY RUN MODE (no API call, no DB write) ---\n")
        print(f"Next version: {next_version}")
        print(f"\nStats: {json.dumps(stats, indent=2)}")
        print(f"\nCategories:")
        for s in sections:
            print(f"  {s['name']}: {s['consensus_status']}, "
                  f"{s['claim_count']} claims, avg {s['avg_composite']}, "
                  f"{len(s['top_claims'])} top claims")
        print(f"\nWould make 2 Claude API calls (narrative + glossary)")
        return

    # --- Generate narrative ---
    print(f"\nGenerating narrative (version {next_version})...")
    narrative = generate_narrative(stats, sections, topic)

    if narrative is None:
        print("ERROR: Failed to generate narrative from Claude.")
        sys.exit(1)

    overall_summary = narrative.get("overall_summary", "")
    category_takeaways = narrative.get("category_takeaways", {})

    # --- Generate glossary ---
    print("Generating glossary...")
    glossary = generate_glossary(overall_summary, category_takeaways)
    if glossary is None:
        print("WARNING: Glossary generation failed — continuing without glossary.")
        glossary = {}
    else:
        print(f"  Glossary: {len(glossary)} terms extracted")

    # Attach takeaways to sections
    for section in sections:
        section["key_takeaway"] = category_takeaways.get(section["name"], "")

    # Assemble final summary_json
    now = datetime.now(timezone.utc).isoformat()
    summary_json = {
        "issue_title": data["issue_title"],
        "generated_at": now,
        "version": next_version,
        "stats": stats,
        "categories": sections,
        "overall_summary": overall_summary,
        "glossary": glossary,
    }

    # summary_text is the overall narrative
    summary_text = overall_summary

    # --- Store ---
    print(f"Storing summary (version {next_version})...")
    success = store_summary(sb, data["issue_id"], next_version, summary_json, summary_text)

    if not success:
        print("ERROR: Failed to store summary.")
        sys.exit(1)

    # --- Output ---
    print(f"\n{'='*60}")
    print(f"SUMMARY GENERATED (version {next_version})")
    print(f"{'='*60}")
    print(f"\nStats:")
    print(f"  Sources: {stats['total_sources']}")
    print(f"  Claims: {stats['total_claims']} ({stats['scored_claims']} scored)")
    print(f"  Strong: {stats['strong_claims']} | Moderate: {stats['moderate_claims']} "
          f"| Mixed: {stats['mixed_claims']} | Weak: {stats['weak_claims']}")

    print(f"\nCategory takeaways:")
    for s in sections:
        takeaway = s.get("key_takeaway", "")
        print(f"  [{s['consensus_status']}] {s['name']}: {takeaway}")

    print(f"\nOverall summary ({len(overall_summary)} chars):")
    print(f"  {overall_summary[:300]}...")


if __name__ == "__main__":
    main()
