"""
Parity Signal: Summary Generation.

Final pipeline step. Assembles claims, scores, and consensus into a structured
JSON summary (for UI) and a plain-language narrative text (for reading).

The structured data (stats, categories, top claims) is computed deterministically
in Python. Only the overall narrative and per-category key takeaways are
generated by Claude (one API call).

Summaries are versioned — re-running creates a new version rather than
overwriting, supporting the evidence update workflow.

Usage:
    cd backend && source venv/bin/activate
    export $(grep -v '^#' .env | xargs)

    python scripts/signal/generate_summary.py --dry-run
    python scripts/signal/generate_summary.py
    python scripts/signal/generate_summary.py   # creates version 2
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# Add backend/ to sys.path so we can import supabase_client
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

GENERATION_MODEL = "claude-sonnet-4-6"
BACKOFF_DELAYS = [2, 5, 10]
CATEGORIES = ["efficacy", "safety", "cardiovascular", "pricing", "regulatory", "emerging"]
TOP_CLAIMS_PER_CATEGORY = 5


# ---------------------------------------------------------------------------
# Anthropic Claude client (lazy singleton)
# ---------------------------------------------------------------------------

_anthropic_client = None


def _get_anthropic_client():
    """Lazy singleton for Anthropic client. Reads ANTHROPIC_API_KEY from env."""
    global _anthropic_client
    if _anthropic_client is None:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            print("ERROR: ANTHROPIC_API_KEY not set.")
            print("  export ANTHROPIC_API_KEY=your_key_here")
            sys.exit(1)
        import anthropic
        _anthropic_client = anthropic.Anthropic(api_key=api_key)
    return _anthropic_client


def _call_claude(system_prompt: str, user_content: str, max_tokens: int = 4096) -> dict | list | None:
    """Call Claude API with retry on 529, return parsed JSON."""
    client = _get_anthropic_client()
    response = None

    for attempt in range(len(BACKOFF_DELAYS) + 1):
        try:
            response = client.messages.create(
                model=GENERATION_MODEL,
                max_tokens=max_tokens,
                temperature=0,
                system=system_prompt,
                messages=[{"role": "user", "content": user_content}],
            )
            break
        except Exception as exc:
            err_str = str(exc)
            if "529" in err_str and attempt < len(BACKOFF_DELAYS):
                delay = BACKOFF_DELAYS[attempt]
                print(f"  [RETRY] Claude overloaded (529), attempt {attempt + 1}/{len(BACKOFF_DELAYS)} in {delay}s...")
                time.sleep(delay)
                continue
            print(f"  [ERROR] Claude API error: {exc}")
            return None

    if response is None:
        return None

    raw_text = ""
    for block in response.content:
        if hasattr(block, "text"):
            raw_text += block.text

    raw_text = raw_text.strip()
    if raw_text.startswith("```"):
        raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text)
        raw_text = re.sub(r"\s*```\s*$", "", raw_text)
    raw_text = raw_text.strip()

    try:
        return json.loads(raw_text)
    except json.JSONDecodeError:
        print(f"  [ERROR] Invalid JSON from Claude: {raw_text[:500]}")
        return None


# ---------------------------------------------------------------------------
# Supabase helpers
# ---------------------------------------------------------------------------

def _get_supabase():
    """Import and return the Supabase client, or exit with message."""
    from supabase_client import supabase as sb
    if sb is None:
        print("ERROR: Supabase client not initialized.")
        print("Set SUPABASE_SERVICE_KEY environment variable before running.")
        sys.exit(1)
    return sb


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_pipeline_data(sb) -> dict:
    """Load all pipeline data needed for summary generation.

    Returns dict with: issue_id, issue_title, claims, composites, consensus, source_count
    """
    # Get the GLP-1 issue
    resp = sb.table("signal_issues").select("id, title").eq("slug", "glp1-drugs").execute()
    if not resp.data:
        print("ERROR: No 'glp1-drugs' issue found. Run earlier pipeline steps first.")
        sys.exit(1)
    issue = resp.data[0]
    issue_id = issue["id"]

    # Count sources
    resp = (
        sb.table("signal_sources")
        .select("id", count="exact")
        .eq("issue_id", issue_id)
        .execute()
    )
    source_count = resp.count or 0

    # Load all claims
    resp = (
        sb.table("signal_claims")
        .select("id, claim_text, category, specificity")
        .eq("issue_id", issue_id)
        .execute()
    )
    claims = resp.data or []

    # Load composites
    claim_ids = [c["id"] for c in claims]
    composites: dict[str, dict] = {}
    chunk_size = 50
    for i in range(0, len(claim_ids), chunk_size):
        chunk = claim_ids[i:i + chunk_size]
        resp = (
            sb.table("signal_claim_composites")
            .select("claim_id, composite_score, evidence_category")
            .in_("claim_id", chunk)
            .execute()
        )
        for comp in (resp.data or []):
            composites[comp["claim_id"]] = comp

    # Load claim-source counts
    source_counts: dict[str, int] = defaultdict(int)
    for i in range(0, len(claim_ids), chunk_size):
        chunk = claim_ids[i:i + chunk_size]
        resp = (
            sb.table("signal_claim_sources")
            .select("claim_id")
            .in_("claim_id", chunk)
            .execute()
        )
        for row in (resp.data or []):
            source_counts[row["claim_id"]] += 1

    # Load consensus
    resp = (
        sb.table("signal_consensus")
        .select("category, consensus_status, summary_text, arguments_for, arguments_against")
        .eq("issue_id", issue_id)
        .execute()
    )
    consensus = {row["category"]: row for row in (resp.data or [])}

    # Attach composites and source counts to claims
    for claim in claims:
        comp = composites.get(claim["id"])
        if comp:
            claim["composite_score"] = float(comp["composite_score"])
            claim["evidence_category"] = comp["evidence_category"]
        else:
            claim["composite_score"] = None
            claim["evidence_category"] = None
        claim["source_count"] = source_counts.get(claim["id"], 0)

    print(f"Loaded pipeline data:")
    print(f"  Issue: {issue['title']}")
    print(f"  Sources: {source_count}")
    print(f"  Claims: {len(claims)} ({len(composites)} scored)")
    print(f"  Consensus mappings: {len(consensus)}")

    return {
        "issue_id": issue_id,
        "issue_title": issue["title"],
        "claims": claims,
        "composites": composites,
        "consensus": consensus,
        "source_count": source_count,
    }


# ---------------------------------------------------------------------------
# Stats and category assembly (deterministic Python)
# ---------------------------------------------------------------------------

def build_stats(data: dict) -> dict:
    """Compute aggregate stats from pipeline data."""
    claims = data["claims"]
    scored = [c for c in claims if c.get("composite_score") is not None]

    cat_counts = defaultdict(int)
    for c in scored:
        cat_counts[c["evidence_category"]] += 1

    return {
        "total_sources": data["source_count"],
        "total_claims": len(claims),
        "scored_claims": len(scored),
        "strong_claims": cat_counts.get("strong", 0),
        "moderate_claims": cat_counts.get("moderate", 0),
        "mixed_claims": cat_counts.get("mixed", 0),
        "weak_claims": cat_counts.get("weak", 0),
    }


def build_category_sections(data: dict) -> list[dict]:
    """Assemble per-category sections with top claims."""
    claims = data["claims"]
    consensus = data["consensus"]

    # Group by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for c in claims:
        by_cat[c.get("category", "emerging")].append(c)

    sections = []
    for cat in CATEGORIES:
        group = by_cat.get(cat, [])
        scored = [c for c in group if c.get("composite_score") is not None]
        scored.sort(key=lambda c: c["composite_score"], reverse=True)

        avg_composite = 0.0
        if scored:
            avg_composite = round(sum(c["composite_score"] for c in scored) / len(scored), 2)

        # Top N claims
        top_claims = []
        for c in scored[:TOP_CLAIMS_PER_CATEGORY]:
            top_claims.append({
                "claim_text": c["claim_text"],
                "composite_score": c["composite_score"],
                "evidence_category": c["evidence_category"],
                "source_count": c.get("source_count", 0),
            })

        cons = consensus.get(cat, {})
        section = {
            "name": cat,
            "consensus_status": cons.get("consensus_status", "uncertain"),
            "consensus_summary": cons.get("summary_text", ""),
            "claim_count": len(group),
            "scored_count": len(scored),
            "avg_composite": avg_composite,
            "top_claims": top_claims,
        }

        if cons.get("consensus_status") == "debated":
            section["arguments_for"] = cons.get("arguments_for", "")
            section["arguments_against"] = cons.get("arguments_against", "")

        sections.append(section)

    return sections


# ---------------------------------------------------------------------------
# Claude narrative generation (one API call)
# ---------------------------------------------------------------------------

NARRATIVE_SYSTEM_PROMPT = """You are a science communicator writing for a general audience. You are generating a summary of the current evidence on GLP-1 receptor agonist drugs (semaglutide/Ozempic/Wegovy, tirzepatide/Mounjaro/Zepbound).

## Rules
- Write in plain language — no medical jargon, no acronyms without explanation
- Do NOT express opinions or recommendations
- Describe evidence strength and consensus, not truth
- Be specific: include key numbers from the top claims where relevant
- Be concise: each key_takeaway is 1-2 sentences, overall_summary is 2-3 paragraphs (~400-500 words)
- Do NOT use phrases like "our analysis shows" — describe what the evidence shows

## Output Format

Return a JSON object:
{
  "overall_summary": "2-3 paragraph plain-language narrative covering all categories. Start with the big picture, then address each evidence area. End with what remains debated or uncertain.",
  "category_takeaways": {
    "efficacy": "1-2 sentence key takeaway for this category",
    "safety": "...",
    "cardiovascular": "...",
    "pricing": "...",
    "regulatory": "...",
    "emerging": "..."
  }
}"""


def generate_narrative(stats: dict, sections: list[dict]) -> dict | None:
    """Send assembled data to Claude for narrative generation.

    Returns {overall_summary, category_takeaways} or None on failure.
    """
    # Build a condensed view of the data for Claude
    parts = [
        f"Evidence Summary Data for GLP-1 Receptor Agonist Drugs",
        f"",
        f"Overall stats:",
        f"  {stats['total_sources']} sources analyzed",
        f"  {stats['total_claims']} claims extracted, {stats['scored_claims']} scored",
        f"  Evidence strength: {stats['strong_claims']} strong, {stats['moderate_claims']} moderate, "
        f"{stats['mixed_claims']} mixed, {stats['weak_claims']} weak",
        f"",
    ]

    for section in sections:
        parts.append(f"--- {section['name'].upper()} ---")
        parts.append(f"Status: {section['consensus_status']}")
        parts.append(f"Claims: {section['claim_count']} ({section['scored_count']} scored, avg score {section['avg_composite']})")
        if section.get("consensus_summary"):
            parts.append(f"Consensus: {section['consensus_summary']}")

        if section.get("arguments_for"):
            parts.append(f"Arguments for: {section['arguments_for']}")
            parts.append(f"Arguments against: {section['arguments_against']}")

        parts.append(f"Top claims:")
        for tc in section["top_claims"]:
            parts.append(f"  [{tc['composite_score']:.2f} {tc['evidence_category']}] {tc['claim_text']}")
        parts.append("")

    user_text = "\n".join(parts)
    return _call_claude(NARRATIVE_SYSTEM_PROMPT, user_text)


# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------

def get_next_version(sb, issue_id: str) -> int:
    """Get the next version number for this issue's summaries."""
    resp = (
        sb.table("signal_summaries")
        .select("version")
        .eq("issue_id", issue_id)
        .order("version", desc=True)
        .limit(1)
        .execute()
    )
    if resp.data:
        return resp.data[0]["version"] + 1
    return 1


def store_summary(sb, issue_id: str, version: int, summary_json: dict, summary_text: str) -> bool:
    """Insert summary row. Returns True on success."""
    row = {
        "issue_id": issue_id,
        "version": version,
        "summary_json": summary_json,
        "summary_text": summary_text,
        "generation_model": GENERATION_MODEL,
    }
    try:
        sb.table("signal_summaries").insert(row).execute()
        return True
    except Exception as exc:
        print(f"  [ERROR] Failed to insert summary: {exc}")
        return False


# ---------------------------------------------------------------------------
# CLI orchestrator
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate structured summary from scored claims and consensus."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show assembled data without API call or DB write",
    )
    args = parser.parse_args()

    sb = _get_supabase()
    data = load_pipeline_data(sb)

    # Build structured sections
    stats = build_stats(data)
    sections = build_category_sections(data)
    next_version = get_next_version(sb, data["issue_id"])

    # --- Dry run ---
    if args.dry_run:
        print(f"\n--- DRY RUN MODE (no API call, no DB write) ---\n")
        print(f"Next version: {next_version}")
        print(f"\nStats: {json.dumps(stats, indent=2)}")
        print(f"\nCategories:")
        for s in sections:
            print(f"  {s['name']}: {s['consensus_status']}, "
                  f"{s['claim_count']} claims, avg {s['avg_composite']}, "
                  f"{len(s['top_claims'])} top claims")
        print(f"\nWould make 1 Claude API call for narrative generation")
        return

    # --- Generate narrative ---
    print(f"\nGenerating narrative (version {next_version})...")
    narrative = generate_narrative(stats, sections)

    if narrative is None:
        print("ERROR: Failed to generate narrative from Claude.")
        sys.exit(1)

    overall_summary = narrative.get("overall_summary", "")
    category_takeaways = narrative.get("category_takeaways", {})

    # Attach takeaways to sections
    for section in sections:
        section["key_takeaway"] = category_takeaways.get(section["name"], "")

    # Assemble final summary_json
    now = datetime.now(timezone.utc).isoformat()
    summary_json = {
        "issue_title": data["issue_title"],
        "generated_at": now,
        "version": next_version,
        "stats": stats,
        "categories": sections,
        "overall_summary": overall_summary,
    }

    # summary_text is the overall narrative
    summary_text = overall_summary

    # --- Store ---
    print(f"Storing summary (version {next_version})...")
    success = store_summary(sb, data["issue_id"], next_version, summary_json, summary_text)

    if not success:
        print("ERROR: Failed to store summary.")
        sys.exit(1)

    # --- Output ---
    print(f"\n{'='*60}")
    print(f"SUMMARY GENERATED (version {next_version})")
    print(f"{'='*60}")
    print(f"\nStats:")
    print(f"  Sources: {stats['total_sources']}")
    print(f"  Claims: {stats['total_claims']} ({stats['scored_claims']} scored)")
    print(f"  Strong: {stats['strong_claims']} | Moderate: {stats['moderate_claims']} "
          f"| Mixed: {stats['mixed_claims']} | Weak: {stats['weak_claims']}")

    print(f"\nCategory takeaways:")
    for s in sections:
        takeaway = s.get("key_takeaway", "")
        print(f"  [{s['consensus_status']}] {s['name']}: {takeaway}")

    print(f"\nOverall summary ({len(overall_summary)} chars):")
    print(f"  {overall_summary[:300]}...")


if __name__ == "__main__":
    main()
