// The password-protected board route, tested as a function.
//
// Run:  node backend/tests/whatholdsup/admin.test.js
//
// The route is generated by publish.py dashboard --web, so these run against
// generated code. That is the point: the generator is what could break, and a
// board that serves itself without a password is the failure that matters.
const path = require("path");
const handler = require(path.join(__dirname, "..", "..", "..", "site", "whatholdsup", "api", "admin.js"));
let pass = 0, fail = 0;
function res() {
  const o = { code: 0, headers: {}, body: "" };
  return { o,
    setHeader: (k, v) => { o.headers[k.toLowerCase()] = v; },
    status: c => { o.code = c; return { send: b => { o.body = b || ""; } }; } };
}
function t(name, env, auth, check) {
  const before = process.env.ADMIN_PASSWORD;
  if (env === null) delete process.env.ADMIN_PASSWORD; else process.env.ADMIN_PASSWORD = env;
  const r = res();
  handler({ headers: auth ? { authorization: auth } : {} }, r);
  if (before === undefined) delete process.env.ADMIN_PASSWORD; else process.env.ADMIN_PASSWORD = before;
  const ok = check(r.o);
  console.log((ok ? "  ok   " : "  FAIL ") + name);
  ok ? pass++ : fail++;
}
const b64 = s => Buffer.from(s).toString("base64");
t("no password set -> 500, no board", null, null, o => o.code === 500 && !o.body.includes("Publication board"));
t("no auth header -> 401 + challenge", "s3cret", null,
  o => o.code === 401 && /^Basic realm=/.test(o.headers["www-authenticate"] || ""));
t("wrong password -> 401", "s3cret", "Basic " + b64("x:nope1"), o => o.code === 401);
t("right length wrong value -> 401", "s3cret", "Basic " + b64("x:s3crft"), o => o.code === 401);
t("correct -> 200 + board", "s3cret", "Basic " + b64("x:s3cret"),
  o => o.code === 200 && o.body.includes("publication board"));
t("correct, empty username -> 200", "s3cret", "Basic " + b64(":s3cret"), o => o.code === 200);
t("no-store + noindex on success", "s3cret", "Basic " + b64("x:s3cret"),
  o => (o.headers["cache-control"] || "").includes("no-store") &&
       (o.headers["x-robots-tag"] || "").includes("noindex"));
t("garbage base64 -> 401", "s3cret", "Basic !!!!", o => o.code === 401);
t("bearer token -> 401", "s3cret", "Bearer s3cret", o => o.code === 401);
t("board folds what is already dealt with", "s3cret", "Basic " + b64("x:s3cret"),
  o => o.body.includes("already dealt with") && o.body.includes("<details"));
t("board never scrolls sideways", "s3cret", "Basic " + b64("x:s3cret"),
  o => !o.body.includes("overflow-x:auto"));
// Copy buttons belong to commands. A board with nothing left to run has no
// commands and should have no buttons — but every command that IS shown must
// have one, or it is a command you have to retype by hand.
t("every command shown has a copy button", "s3cret", "Basic " + b64("x:s3cret"),
  o => (o.body.match(/<div class="cmd">/g) || []).length
       === (o.body.match(/button class="copy"/g) || []).length);
t("board never offers a bare gate re-run as the next step", "s3cret", "Basic " + b64("x:s3cret"),
  o => !/Next[\s\S]{0,400}factcheck_draft\.py/.test(o.body));
t("signed-off steps are marked, not left amber", "s3cret", "Basic " + b64("x:s3cret"),
  o => !o.body.includes("accept-gate") || o.body.includes("signed off"));
console.log("\n  " + pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
